### ISSUE TITLE
Cannot modify JLC webcam settings on M1 Mac Mini

### ISSUE THREAD

**Issue by manighahrmani** [Itaybre/CameraController#109]
**Describe the bug**
Cannot modify any of the settings

**To Reproduce**
1. Using a JLC camera on M1 Mac Mini
2. None of the settings are modifiable as shown in the screen capture attached.

**Expected behavior**
I was hoping I could increase the exposure of the camera.

**Screenshots**
See attached.

**Desktop (please complete the following information):**
 - Version 1.4.0
 - Camera JLC 2K Optic Webcam

**Additional context**
None.
![image](https://github.com/Itaybre/CameraController/assets/12306646/3ba69996-ca5c-44d9-a503-2526a18aa817)

**Comment by Itaybre** [comment]
If it is disabled, it means the camera doesn't support this feature.
