### ISSUE TITLE
Zoom/Pan/tilt not working

### ISSUE THREAD

**Issue by anoopmg** [Itaybre/CameraController#114]
tried the camera controller application in my external display with built in camera.
features in Basic tab working fine, but features are in Advanced tab was not working.
All the sliders in advanced tab is disabled state.
While checking with UVC-util application,Capability for zoom, tilt,pan are seems to available.

Did I missed something or suggest me some methods for debugging this issue.

Mac OS : 13.3
Mac model : M2, Mac book Pro

**To Reproduce**
1. Go to CameraController app
2. Click on Advanced tab
3. Scroll down to Zoom/Pan/tilt section
4. See error : Zoom/pan/tilt sliders are disabled state

**Expected behavior**
Zoom/pan/tilt sliders are in active state

**Screenshots**

**Desktop (please complete the following information):**
 - Version [13.3]
<img width="429" alt="Screenshot-camera-controls" src="https://github.com/Itaybre/CameraController/assets/1148222/c417a721-8dd2-4701-a413-a8f0fa301e39">

 - Camera [Built in External display camera]

**Comment by Itaybre** [comment]
It means these features are not compatible with your camera
