### ISSUE TITLE
Big Sur 11.5 unable to launch app after download

### ISSUE THREAD

**Issue by UziKhana** [Itaybre/CameraController#13]
Expected behaviour:
1. download app
2. launch app
3. get third party app warning/caution note
4. goto Settings > Security & Privacy and click Open Anyway
5. app opens

What is happening:

1. download app
2. launch app
3. get third party app warning/caution note
4. get CameraController quit unexpectedly message (see screenshot) 

![Screen Shot 2021-08-09 at 09 11 49 AM](https://user-images.githubusercontent.com/69767649/128663085-ac110c95-18c3-474d-9f0c-77b286f6d7d3.png)

4. goto Settings > Security & Privacy, there is no button for Open Anyway
5. click Reopen, settings > Security & Privacy flickers a bit but still o button for Open Anyway

Other symptom:
1. app icon disabled (screenshot attached) 

![Screen Shot 2021-08-09 at 09 16 41 AM](https://user-images.githubusercontent.com/69767649/128663104-8ae17834-efd8-46e8-882b-c4dbca0b540b.png)

Result:
Unable to open the app since first download

**Comment by Itaybre** [comment]
@UziKhana thanks for the ticket, may I know which camera are you using?

Can you also try this build: https://github.com/Itaybre/CameraController/files/6825344/CameraController.zip ?
This one has a fix for some cameras

**Comment by Itaybre** [comment]
Should be fixed on [1.3](https://github.com/Itaybre/CameraController/releases/tag/1.3)
Please reopen if not fixed

**Comment by UziKhana** [comment]
Hey thanks for taking this on. I shall try shortly. I am using Dell 4k ultrasharp camera (sorry I missed responding to your earlier message).

**Comment by UziKhana** [comment]
Still getting this, I have a also tried CamLink 4k

![Screen Shot 2021-08-23 at 10 03 07 AM](https://user-images.githubusercontent.com/69767649/130399647-3fe707dd-eef4-457d-942c-857df5ce4920.png)
