### ISSUE TITLE
AVFoundation?

### ISSUE THREAD

**Issue by binba2** [Itaybre/CameraController#130]
UVC is ancient, how about updating CameraController to utilize AVFoundation?

Everywhere I look for discussions about whether, how, or why controlling modern Macs' (built-in Facetime HD) webcams doesn't work, there's never any -- there are no replies, no discussion.

**Comment by Itaybre** [comment]
UVC is how computer communicate with USB camera (**U**SB **V**ideo **C**lass).

AVFoundation provides no API to communicate directly to the camera. You can see in the [FAQ](https://github.com/Itaybre/CameraController?tab=readme-ov-file#faq) section why built in FaceTime cameras cannot be controller.
