### ISSUE TITLE
Add ability to adjust a setting by setting a value explicitly rather than with a slider

### ISSUE THREAD

**Issue by globau** [Itaybre/CameraController#19]
Sometimes I want to set a control to a specific value; right now this isn't possible as there's no way to either see or set the value of a control.

Webcam Settings does this by changing the widget from a slider to a text field when you click on a field's label:

<img width="379" alt="Screen Shot 2021-09-01 at 4 07 57 pm" src="https://user-images.githubusercontent.com/872825/131635930-0e2ca05b-f5ce-4799-baab-efcdc51262a0.png">

**Comment by Itaybre** [comment]
I have created a build with this, do you mind testing it?

Double tap the controller name to enable the field
[CameraController.zip](https://github.com/Itaybre/CameraController/files/7898077/CameraController.zip)
