### ISSUE TITLE
Brightness can only be increased, not decreased

### ISSUE THREAD

**Issue by benblb** [Itaybre/CameraController#22]
**Describe the bug**
Unable to reduce camera brightness, but I can increase it. 

**To Reproduce**
1. Go to basic settings
2. Click on brightness
3. Drag slider all the way to the left
4. See "normal" brightness. 

**Expected behavior**
Ability to decrease brightness in addition to increasing. Image should get darker than the cam's default. 

**Desktop (please complete the following information):**
 - Big Sur 11.6
 - Camera Depstech DW49 (4k)

**Comment by Itaybre** [comment]
@benblb I have not been able to reproduce this, can you submit a demo of the issue?

**Comment by benblb** [comment]
Absolutely! https://imgur.com/a/E40KEVm

When the slider is all the way to the left, that is what the camera looks like without any modifications (i.e. default brightness).

**Comment by replete** [comment]
I am getting this with bug also with an Aukey 1080p HD webcam, which shows up as 'PC-LM1E'.

I increased the brightness via the slider, but moving the slider to the left results in no changes being applied - and there appears to be no way to reset this.
