### ISSUE TITLE
Sliders do not reliably display/apply active setting when switching Auto mode on/off

### ISSUE THREAD

**Issue by bstrand** [Itaybre/CameraController#24]
**Description**
There are two aspects to this issue. Depending on what the desired behavior is, 
1. When one switches 'auto' mode from off to on, the sliders for the controlled settings are not updated to reflect the active value.
2. When auto mode is switched from on to off and the indicated setting on the slider is different from the active, auto-set value, the indicated setting is not applied. (One must move the slider to get it to apply.)

If the intent is indeed to allow manual settings to persist on the sliders when auto is switched on, then they should be immediately reapplied when auto is switched off, i.e., point 2.

However, imo the more desirable behavior would be for the settings controls to always accurately reflect their active values, which would require addressing point 1.  
Arguments in favor of this behavior: 
* Reflecting the automatically applied value for the setting in the manual controls provides the user with useful information about how the camera is configured and whether it may be useful to manually override. 
* Persisting manual settings can still be done by saving to a profile

A third possibility: when switching to Auto mode, to internally retain the manual settings while displaying the auto-set values in the sliders. Then, on switching back to Manual mode, restore those manual settings. This would give the user the ability to easily iteratively tune manual settings to improve on Auto mode's results. And it would serve as a "quick switch" to enable/disable subsets of manual settings in saved profiles.

**To Reproduce**
1. Start with defaults, Auto mode enabled everywhere
2. Switch Exposure/Mode to Manual
3. Increase Exposure/Gain slider to maximum
    Result: image washed out
4. Switch Exposure/Mode to Auto
    Result: image optimizes; Exposure/Gain slider does not change, remains at maximum
    Expected: image returns to normal; Exposure/Gain slider changes to active, auto-set value
6. Switch Exposure/Mode to Manual
     Result: image remains normal, indicating gain remains at auto-set value; Gain slider remains at maximum
     Expected: Setting reflected by slider (max) is applied; image washes out 

**Environment**
 - CameraController: v1.3 (5)
 - Camera: Razer Kiyo
 - OS: MacOS 10.15.7

**Comment by Itaybre** [comment]
This is definitely a bug, and I am still exploring on how to fix it.
Oddly enough, if the camera has set Exposure to Manual when you start CameraController, after you change it to Auto, sliders update automatically (if you have Read Settings enabled)
![image](https://user-images.githubusercontent.com/860036/139678324-eab86d74-09e6-41ea-9b21-003c4af0b411.png)
