### ISSUE TITLE
Feature request: UI should expose (editable) numbers

### ISSUE THREAD

**Issue by wookayin** [Itaybre/CameraController#30]
Currently, all the settings are configurable via sliders, which do not provide an exact number.

<img src="https://user-images.githubusercontent.com/1009873/143470109-4e506592-c94e-42fe-885c-dfe66c36d721.png" width=600 />

**Feature request**: The UI should expose readouts of numbers (and preferably their valid ranges if space allows) and they should be editable to allow users to enter the values manually. Of course, sliders and text boxes should be synchronized with some reasonable sanity check.

This is an important feature for more fine-grained control. Thank you!

**Comment by wookayin** [comment]
@Itaybre still yet?

**Comment by Itaybre** [comment]
I just built a version with this, but I cannot test it because I don't have my webcam with me, do you mind giving it a test?

Double Tap the controller name to be able to edit it
[CameraController.zip](https://github.com/Itaybre/CameraController/files/7898073/CameraController.zip)

**Comment by Itaybre** [comment]
@wookayin please use this one, that one didn't link the field with the camera 
[CameraController.zip](https://github.com/Itaybre/CameraController/files/7898946/CameraController.zip)
values

**Comment by wookayin** [comment]
@Itaybre Are you sure this is the correct build? The UI hasn't changed.

**Comment by wookayin** [comment]
Oh I see, when you double click it toggles between slider and textbox. Personally I don't feel this is an intuitive design. Why don't you put the input box next to the sliders so they can be shown at the same time? IMO there is no need to toggle...

**Comment by Itaybre** [comment]
@wookayin I wouldn't consider it final, but I don't want to clutter the interface with too many buttons.

I am open to options, like enabling this from preferences

**Comment by wookayin** [comment]
@Itaybre could you please this re-open unless you really don't want to not implement this? (Personally I don't like stalebot keep closing the issues..)

**Comment by Eloren1** [comment]
??????????????? I literally cannot check my shutter speed. Who thought about doing it sliders only?

**Comment by Eloren1** [comment]
@itaybre

**Comment by Eloren1** [comment]
> don't want to clutter the interface

A good interface is simple to use, it should be comfortable for both pros and noobs, and outputting exact values is useful for everyone. Blank sliders are so weird.
