### ISSUE TITLE
I have the Monterey update for mac and the zoom option doesn't work with the razer kiyo. Any way that your team could fix this?

### ISSUE THREAD

**Issue by Benisprung** [Itaybre/CameraController#34]
Worked great until I downloaded OS 12 on my mac, now I can not find anything that works with the zoom for the Razer Kiyo. Everything else is still in tact and works smoothly. Any recommendations?

**Comment by Michael-Bischof** [comment]
@Benisprung Works fine with my Razer Kiyo when using Camera Controller 1.3.1 on macOS Montery 12.1 (21C52)

Maybe try removing Camera Controller and downloading it fresh?
