### ISSUE TITLE
Enable mirror/flip option

### ISSUE THREAD

**Issue by imacnu** [Itaybre/CameraController#39]
Please add an option to mirror or flip camera image (basically to Google Meet)

Mac OSX 15
Logitech BC950

Thanks.

**Comment by chansearrington** [comment]
I'd like to second this request. Can this be re-oppened?

My cameras are mounted upside down because of how they need to be placed. And I'm able to Mirror (flip horizontal) or Flip (flip vertically) in other apps like eCamm Live but not in this app.
