### ISSUE TITLE
Exposure Time Input not working - Razer Kiyo

### ISSUE THREAD

**Issue by robooneus** [Itaybre/CameraController#40]
**Describe the bug**
Switching from Auto to Manual in the exposure settings - the first change to the exposure time setting darkens the image significantly, then further changes have no effect whatsoever. This leads to, with max Gain and max exposure time, an image significantly darker than needed.

**Desktop (please complete the following information):**
 - Version 1.3.1 (6)
 - Camera - Razer Kiyo

**Additional context**
Workaround is to switch to "auto" exposure, then change only gain settings. However, the "auto" exposure time is overriden when starting the camera again. e.g. new zoom call.

**Comment by carlosnasillo** [comment]
Experiencing the same with the Razer Kiyo Pro
