### ISSUE TITLE
Programm Crash when started

### ISSUE THREAD

**Issue by Scybe1** [Itaybre/CameraController#42]
Hey together- I am new here. i was searching for absolutely the programm you coded. Problem is, just the version 1.2 is working. higher ones does not work. I am Using MAC OS 10.15.7 on a Macbook Pro 2013 16 GB.

Is there something i could change to run the programm ?

Thank you very much !!
[Crash Report1.3.1.txt](https://github.com/Itaybre/CameraController/files/8020272/Crash.Report1.3.1.txt)

**Comment by joekw** [comment]
I'm seeing this too. Looks like `uvcUnit` is set to -1.

**Comment by atchinson** [comment]
Do you have OBS Studio installed on your Mac or some other virtual non usb camera? Sometimes the app works, most of the time it crashes complaining about a negative number.

My other Mac without OBS seems to work fine.

**Comment by jazzychad** [comment]
I have opened a PR for this issue: https://github.com/Itaybre/CameraController/pull/57

**Comment by jazzychad** [comment]
This can probably be closed now? (unless you want to cut another release first?)

**Comment by Itaybre** [comment]
You are right, closing it now
