### ISSUE TITLE
Add rotate image

### ISSUE THREAD

**Issue by davidindub** [Itaybre/CameraController#48]
Excellent job with the app - I've been looking for something to replace the Logi software for my camera, it still isn't M1 compatible and I have a shiny new MacBook on the way!

Unfortunately the Logitech Streamcam doesn't auto rotate to portrait on macOS despite it being one of its main advertised features, so the ability to rotate the picture would be really useful.

See: [Reddit - Streamcam auto-rotate doesn't work in Big Sur or Monterey MacOS](https://www.reddit.com/r/logitech/comments/rfipeq/streamcam_autorotate_doesnt_work_in_big_sur_or/)

**Setup:**

- macOS Monterey 12.2.1
- 2.3 GHz Dual-Core Intel Core i5 / 8GB Memory
- Logitech Streamcam

**Comment by Itaybre** [comment]
This doesn't seem to be part of the USB Standard, probably Logitech is doing something on Windows for that feature (doesn't seem to be working on Linux either)
