### ISSUE TITLE
GoPro Hero 10 not recognized

### ISSUE THREAD

**Issue by FezVrasta** [Itaybre/CameraController#53]
Please enter the following data:

Brand: GoPro
Camera: Hero 10
Have you tried many USB ports? Yes

**Comment by Itaybre** [comment]
CameraController requires the camera to comply to UVC Standard.
I don't really know if the GoPro meets the criteria, for example, can you use it for FaceTime / Photo Booth?

**Comment by FezVrasta** [comment]
Thanks for the answer. No I can't used it with Photo Boot or FaceTime, I can use it with any browser, Zoom, and other apps though.

**Comment by olebedev** [comment]
Same problem with GoPro 8 Hero Black.

**Comment by olebedev** [comment]
Any chance you can look at make the CameraController work with  not UVC compliant cameras like GoPro? That would be awesome.

Anyways, thanks for the great project!

**Comment by Itaybre** [comment]
@olebedev Probably no, it requires the camera itself to have such feature, usually it is down with the UVC standard.

Browsing GoPro website, we can see that their utility doesn't even support changing these settings, so the answer is now (but if they add support via a firmware update in the future, I can add support for it)

**Comment by olebedev** [comment]
@Itaybre, got it, thanks for the explanation. Good to know :)
