### ISSUE TITLE
Zooming functionality ?

### ISSUE THREAD

**Issue by renaudguerin** [Itaybre/CameraController#54]
Hi,

Great app !
I've just installed it and Zoom/Pan/Tilt is greyed out.
I wonder if this is a purely hardware implemented feature (no chance it will ever work if my webcam doesn't have it) ?

Thanks 

Brand:  Jelly Comb
USB info :
FHD Camera Microphone
  Product ID:	0x28c4
  Vendor ID:	0x1bcf  (Sunplus Innovation Technology Inc.)

**Comment by Itaybre** [comment]
If it is greyed out, it means that your camera doesn't support it, or at least not using the standard UVC protocol
