### ISSUE TITLE
Zoom/pan/tilt options are grayed out with AUKEY PC-LM1E

### ISSUE THREAD

**Issue by RobertoMinelli** [Itaybre/CameraController#55]
Dear @Itaybre, zoom/pan/tilt functions are not available with my [AUKEY PC-LM1E](https://www.aukey.com/products/aukey-overview-full-hd-video-1080p-webcam) (see screenshot). I already tried multiple USB ports. Can you please help me?

Best,
Roberto

<img width="435" alt="Screen Shot 2022-04-13 at 12 08 59" src="https://user-images.githubusercontent.com/6087804/163155681-41c53926-ba25-4334-a69f-487bfeaac747.png">

**Comment by Itaybre** [comment]
If it is disabled it means, that these actions are not supported.
Not all cameras support all operations.

You can check which options are supported using the app here: https://github.com/Itaybre/CameraController/issues/3#issuecomment-671698003
