### ISSUE TITLE
Can't control Zoom/Pan/Tilt for Lenovo FHD Webcam

### ISSUE THREAD

**Issue by kiran-vemuri** [Itaybre/CameraController#56]
I'm running on M1 Mac mini with a USB webcam (Lenovo 300 FHD Webcam)
![Screenshot 2022-04-14 at 4 12 13 AM](https://user-images.githubusercontent.com/1210749/163281989-4f88a56b-f42d-4a81-a989-11aa608d5f60.png)

**Comment by Itaybre** [comment]
If it is disabled it means, that these actions are not supported.
Not all cameras support all operations.

You can check which options are supported using the app here: https://github.com/Itaybre/CameraController/issues/3#issuecomment-671698003
