### ISSUE TITLE
Doesn't open on M1 Pro 

### ISSUE THREAD

**Issue by Rawnly** [Itaybre/CameraController#64]
**Describe the bug**
Doesn't open. it "quits unexpectedly"

**To Reproduce**
1. Open the app 

[Here a crash log](https://pastebin.com/sPuv5KWg) (pastebin password is: `camera controller`)

**Expected behavior**
Open the app

**Screenshots**
![CleanShot 2022-05-23 at 12 32 13](https://user-images.githubusercontent.com/16429579/169800737-047f6d1e-67df-44f9-b0d9-bfd57455cb1f.png)

**Desktop (please complete the following information):**
 - Version 1.3.1
 - Camera Aukey PC-LM1E

**Comment by jazzychad** [comment]
This was fixed by edb2d4fdb3cb2547d2cfcfdc9d3b3d9dd4dc7fc2
https://github.com/Itaybre/CameraController/commit/edb2d4fdb3cb2547d2cfcfdc9d3b3d9dd4dc7fc2

It is available in the latest 1.4.0 release: https://github.com/Itaybre/CameraController/releases/tag/v1.4.0

**Comment by Rawnly** [comment]
Ok thanks! You might need to update the homebrew release too (i installed it this morning and i got the 1.3.1!)

**Comment by jazzychad** [comment]
aha.. might need to file a separate issue for that!
