### ISSUE TITLE
Update `homebrew` release

### ISSUE THREAD

**Issue by Rawnly** [Itaybre/CameraController#65]
**Describe the bug**
I tried to install the app via `homebrew` but I didn't got the latest version.

**To Reproduce**
```sh
brew --cask install cameracontroller
```

**Expected behavior**
To get the latest release installed

**Comment by Itaybre** [comment]
Just sent a PR to `homebrew` to update it

**Comment by Itaybre** [comment]
It has been merged, you can download v1.4.0.
I will take a note to remember updating the cask when releasing a new version
