### ISSUE TITLE
None of the Controls work on M1 MacBook

### ISSUE THREAD

**Issue by homurahomu1** [Itaybre/CameraController#66]
Hey, I think this app is really nice, but I recently downloaded it on my M1 MacBook Pro(14") to tweak some of the camera settings and nothing works. The preview shows, but none of the controls work at all. If someone could fix this I would be very grateful
<img width="562" alt="Screen Shot 2022-05-24 at 4 53 42 pm" src="https://user-images.githubusercontent.com/69967456/169967412-fcd8b230-f73b-43ed-a8bb-afbccbba2164.png">
!

**Comment by jazzychad** [comment]
AFAIK, this app does not work with the FaceTime camera, but only with other UVC-compatible USB webcams attached to the computer.

**Comment by Itaybre** [comment]
It is as @jazzychad said, apple doesn't allow communication with the FaceTime Camera without special entitlements.
This is why CameraController cannot change settings for it
