### ISSUE TITLE
Can't reopen UI after closing it

### ISSUE THREAD

**Issue by MatanRubin** [Itaybre/CameraController#7]
**Describe the bug**
After closing the UI (using Cmd+W or hitting the red X button), there's no way to reopen it. Clicking the app icon does nothing, while I expected it to reopen the UI.

**To Reproduce**
1. Open the app
2. Close the UI using Cmd+W
3. Click the app icon in the Dock
4. Nothing happens

**Expected behavior**
The UI reopens.

**Desktop (please complete the following information):**
 - Version 1.2 (3)
 - Logitech C920
 - macOS Big Sur

**Comment by Itaybre** [comment]
@MatanRubin thanks for the report, will take a look
