### ISSUE TITLE
Profile Location

### ISSUE THREAD

**Issue by antonmil** [Itaybre/CameraController#75]
More of a question than an issue, really. I'm wondering where I can find the file that's saved to disk as a profile. I'm asking because I want to transfer it to a different machine to work with the same camera and settings. Perhaps one could give the user a hint on the UI about that.

**Comment by Itaybre** [comment]
Sorry for the delay, profiles are saved with the UserDefaults class.
The data is stored at `~/Library/Containers/com.itaysoft.CameraController/Data/Library/Preferences/com.itaysoft.CameraController.plist`

I will add a feature to export and import profiles in a future version
