### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by herrerajeff** [Itaybre/CameraController#8]
I've been looking for something like this for so long! I'm a designer and have been searching forever. Saw you needed an app icon, so I made one as a thank you!

Jeff Herrera
[jeffreyherrera.com](https://www.jeffreyherrera.com) | [twitter](https://www.twitter.com/isthatjeff) | [linkedin](https://www.linkedin.com/in/jeffrey-herrera)

<img width="658" alt="image" src="https://user-images.githubusercontent.com/13124809/117867670-a8015500-b266-11eb-9e82-011cd1206564.png">

[CameraController.icns.zip](https://github.com/Itaybre/CameraController/files/6461326/CameraController.icns.zip)

**Comment by Itaybre** [comment]
Thanks, it looks great, I will change it ASAP

Could you also create a matching icon for the status bar?

**Comment by herrerajeff** [comment]
Status bar had to be a bit simpler but here we are: 

<img width="339" alt="image" src="https://user-images.githubusercontent.com/13124809/121085380-c5670780-c7af-11eb-933b-cd6924710671.png">


[Camera Controller Menu Icon.zip](https://github.com/Itaybre/CameraController/files/6611923/Camera.Controller.Menu.Icon.zip)
