### ISSUE TITLE
Test error: No signing certificate "Mac Development" found

### ISSUE THREAD

**Issue by Sid110307** [Itaybre/CameraController#80]
> **To fix the issue:**
> 
> Head to Project -> Build Settings.
> At the top, click Build Settings.
> Scroll down to "Signing", and click "Code Signing Identity".
> Set it to "Sign to run locally".
> Then scroll down a little and find "Code Signing Style", and set it to "Manual".

**Comment by Itaybre** [comment]
Old certificate expired, working with a new one 💪
