### ISSUE TITLE
Zoom Pan Tilt not working for Microsoft Modern WebCam

### ISSUE THREAD

**Issue by sadiqkhoja** [Itaybre/CameraController#85]
I am trying to set Zoom, Pan and Tilt for "Microsoft Modern Webcam" on MacBook Air M2, I can move the slider but nothing happens, I am attaching UBS Bus Probe here:

[USB Bus Probe.txt](https://github.com/Itaybre/CameraController/files/10099378/USB.Bus.Probe.txt)

![Untitled](https://user-images.githubusercontent.com/447837/204164229-fb8a87b0-7f3f-4d2b-b20b-83c6cde2cb6e.jpg)

**Comment by Itaybre** [comment]
With the resolution at max, changing the zoom value does nothing.
This is how most cameras work, the digital zoom won't work if you are using the max resolution

**Comment by Itaybre** [comment]
@konopielko  You will need to do that on the app that is streaming, they usually have a configuration for that

**Comment by Itaybre** [comment]
> > @konopielko You will need to do that on the app that is streaming, they usually have a configuration for that
> 
> I only use my webcam for video meetings, and zoom or google meet don't have settings like that - so is the only solution to use a program like obs as a pass though for the video feed?

Both Zoom and Google meet have an option for that
