### ISSUE TITLE
High pitched buzzing after macOS update

### ISSUE THREAD

**Issue by neveronawednesday** [Itaybre/CameraController#86]
Updated MacBook Air (M2 chip) to macOS Ventura 13.0.1 today,  now getting a high-pitched buzzing sound coming from my Razer Kiyo when using CameraController. 

I have deleted and reinstalled the app, and restarted my mac - the sound is still there.
When I just use the Kiyo by itself with CameraController uninstalled, I don't get the high-pitched buzzing sound.

**Comment by Itaybre** [comment]
Does this happen with just launching the app without changing anything?

**Comment by Itaybre** [comment]
With a little Googling, seems to be related to Auto Focus
