### ISSUE TITLE
1.4.0 no longer works with Zoom 5.13.3 

### ISSUE THREAD

**Issue by ClassicStocksy** [Itaybre/CameraController#89]
**Describe the bug**
I've been happily using 1.4.0 on macOS 11.6.3 with my NexiGo N940P webcam to fix bad room lighting.
Today after updating Zoom to 5.13.3, CameraController no longer works at the same time as Zoom.

If Zoom is launched first, CameraController has greyed-out controls for the camera. If CameraController is launched first, Zoom seems to "grab the controls" and the controls in CameraController are no longer responsive.
With Zoom shut down, CameraController works fine.

I'd guess Zoom added some new features that control the camera and are grabbing the controls here. Obviously this is not a bug caused by CameraController; but thought it would be valuable to have a bug open for those coming back from festive break and wondering what happened to CameraController.

Zoom does not immediately re-write all the camera settings, so it's at least possible to fix the lighting in CameraController and then start Zoom

**Comment by Itaybre** [comment]
I am using build 5.13.3 and everything seems to be working, I was able to edit all the configurations
<img width="2256" alt="image" src="https://user-images.githubusercontent.com/860036/210889417-a6172243-0799-4aee-b19a-9cc4e09eb1fd.png">
