### ISSUE TITLE
Push and read settings

### ISSUE THREAD

**Issue by nomasprime** [Itaybre/CameraController#9]
Everything's very intuitive except I'm not sure what these settings are for. I'd guess it's something to do with OS interference but not sure or how to use them?

PS Third party camera with Apple was painful. Thank you so much for this app 👍

**Comment by Itaybre** [comment]
I am glad you are enjoying Camera Controller.

Some cameras may update its values using a remote controller or through automatic procedures (like brightness or exposure), Read and Push Settings are meant to provide a "up to date" value from the Camera and force values set from the app.

I will try to add a helper so future users can get a better idea about the options.
